name: Deploy to IONOS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_ed25519" \
            --exclude='.git*' \
            --exclude='pflops_data.json' \
            --exclude='pflops_cron.log' \
            --exclude='collect_pflops.js' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/amadeus/
      - name: Rsync testnet
        run: |
          sed -i "s|https://nodes.amadeus.bot|https://testnet-rpc.ama.one|g; s|wss://nodes.amadeus.bot|wss://testnet-rpc.ama.one|g" script.js
          sed -i "s|Amadeus Blockchain Explorer|Amadeus Testnet Blockchain Explorer|g" index.html
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_ed25519" \
            --exclude='.git*' \
            --exclude='pflops_data.json' \
            --exclude='pflops_cron.log' \
            --exclude='collect_pflops.js' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/testnet-explorer/
